search:
  beam_width: 8
  max_depth: 12
  max_nodes: 512
  dedupe: true
  partial_evaluation: true
  record_trace: false

heuristics:
  coverage_weight: 1.0
  depth_penalty: 0.05
  guard_penalty: 0.2
  latency_weight: 0.02
  pending_penalty: 0.01

scoring:
  policy: 0.0
  heuristic: 1.0
  latency_penalty: 0.05
  reuse_bonus: 0.2
