seed: 2468
model:
  input_dim: 32
  hidden_dim: 64
  action_dim: 8
dataset:
  num_trajectories: 4
  trajectory_length: 6
  input_dim: 32
  action_dim: 8
  seed: 2468
training:
  epochs: 2
  batch_size: 8
  minibatch_size: 8
  learning_rate: 0.005
  gamma: 0.99
  gae_lambda: 0.95
  clip_coef: 0.2
  value_coef: 0.5
  entropy_coef: 0.01
  checkpoint_dir: data/processed/checkpoints/rl
  log_interval: 1
