seed: 1337
model:
  input_dim: 32
  hidden_dim: 64
  action_dim: 8
dataset:
  num_samples: 64
  input_dim: 32
  action_dim: 8
  seed: 1337
training:
  epochs: 2
  batch_size: 8
  learning_rate: 0.01
  checkpoint_dir: data/processed/checkpoints/supervised
  log_interval: 1
