version: 1
disable_existing_loggers: false
formatters:
  praxis:
    format: "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: praxis
    stream: ext://sys.stderr
loggers:
  praxis:
    level: INFO
    handlers: [console]
    propagate: false
  praxis.telemetry:
    level: DEBUG
    handlers: [console]
    propagate: false
root:
  level: WARNING
  handlers: [console]
