name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install Poetry
        run: pip install poetry
      - name: Install Python dependencies
        run: poetry install --no-interaction --no-root
      - name: Run lint suite
        run: poetry run bash scripts/lint_ci.sh
      - name: Run Python tests with coverage
        run: poetry run pytest
      - name: Run Rust tests
        run: cargo test -q
      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin --locked
      - name: Rust coverage (vm_runtime)
        run: cargo tarpaulin --locked --package praxis_vm_runtime --fail-under 0
      - name: Rust coverage (verifier_native)
        run: cargo tarpaulin --locked --package praxis_verifier_native --fail-under 0

  nightly:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install Poetry
        run: pip install poetry
      - name: Install Python dependencies
        run: poetry install --no-interaction --no-root
      - name: Run evaluation suites
        run: |
          poetry run python scripts/eval_suite.py --suite regression --suite arc_suite --suite leetcode_easy
      - name: Run proof-heavy Rust tests
        run: cargo test -q --all --release
